### ISSUE TITLE
Add Accept-Ranges: bytes check

### ISSUE THREAD

**Issue by stnvh** [stnvh/php-partialzip#3]
Just times out after 15 seconds currently

@hempalex

**Comment by hempalex** [comment]
You can try to get range: 0-1 in init() and check result headers as well you checking download size

**Comment by stnvh** [comment]
This wouldn't work, as if the server doesn't support byte ranges, it will start to receive the whole file. 

The best thing would be to check for the existence of the Accept-Ranges header in the first request made to get the file size from the server ([Zip.php:82](https://github.com/stnvh/php-partialzip/blob/master/src/Stnvh/Partial/Zip.php#L82))

**Comment by stnvh** [comment]
Fixed in [0.1.5](https://github.com/stnvh/php-partialzip/releases/tag/0.1.5)
